Story Editor View 추가
boostcampwm2023/iOS04-HeatPick pull request #143
Opened 2023-11-16 10:07 UTC by jungmin-lim

## 🌁 배경
* #53 

## ✅ 수정 내역
* 스토리 에디터에 필요한 기본 view를 추가했습니다.

## 📕 리뷰 노트
* category 선택 picker view는 디자인을 조금 더 손 보고 싶어서 개선 중에 있습니다. 

## 🎇 스크린샷
![image](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/32038936/afd6dfff-9d2c-4bb1-bb42-a0e061ac5522)

2023-11-16 10:11 UTC, junbok97 approved these changes
고생하셨슴돠 ~ UI는 이쁜게 최고죠

2023-11-16 10:11 UTC, junbok97 commented on client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/DescriptionField.swift
> +        textField.layer.cornerRadius = 16
요고 Constants에 있습니당 mediumRadius가 16이에영

2023-11-16 10:15 UTC, hogumachu requested changes
고생하셨습니다!
디자인가이드에는 왼쪽 오른쪽 마진이 다 동일한데 한번더 20씩 들어간 부분이 있는 것 같아요!
아래 이미지는 피그마에 있는 이미지 입니다!

<img width="684" alt="스크린샷 2023-11-16 오후 7 13 47" src="https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/30b8e2e7-aa67-4a4d-a19e-e8b26bcc0cd4">

2023-11-16 10:24 UTC, jungmin-lim commented
> 고생하셨습니다! 디자인가이드에는 왼쪽 오른쪽 마진이 다 동일한데 한번더 20씩 들어간 부분이 있는 것 같아요! 아래 이미지는 피그마에 있는 이미지 입니다!
> 
> <img alt="스크린샷 2023-11-16 오후 7 13 47" width="684" src="https://user-images.githubusercontent.com/74225754/283413971-30b8e2e7-aa67-4a4d-a19e-e8b26bcc0cd4.png">

헉 이게 안보였네요...

2023-11-16 10:30 UTC, jungmin-lim commented
> 고생하셨습니다! 디자인가이드에는 왼쪽 오른쪽 마진이 다 동일한데 한번더 20씩 들어간 부분이 있는 것 같아요! 아래 이미지는 피그마에 있는 이미지 입니다!
> 
> <img alt="스크린샷 2023-11-16 오후 7 13 47" width="684" src="https://user-images.githubusercontent.com/74225754/283413971-30b8e2e7-aa67-4a4d-a19e-e8b26bcc0cd4.png">

UI 생각안하고 `ContentConfiguration` 사용해서 생긴 문제네요.
custom TableViewCell 만들면서 tableView inputView에 picker 추가해볼 수 있을 것 같습니다. 👍

2023-11-17 01:49 UTC, hogumachu approved these changes
고생하셨습니동 ! 짱짱

2023-11-17 01:55 UTC, merged